export const journalConstants = {
    GETALL_REQUEST: 'JOURNALS_GETALL_REQUEST',
    GETALL_SUCCESS: 'JOURNALS_GETALL_SUCCESS',
    GETALL_FAILURE: 'JOURNALS_GETALL_FAILURE',
    LOAD_NEXT_SUCCESS: 'LOAD_NEXT_SUCCESS',
    QUICK_FILTER_CHANGE: 'QUICK_FILTER_CHANGE',
    NO_MORE_JOURNALS: 'NO_MORE_JOURNALS',
    PAGE_SIZE: 20
};
