function mobile(){var Q='bootstrap',R='begin',S='gwt.codesvr.mobile=',T='gwt.codesvr=',U='mobile',V='startup',W='DUMMY',X=0,Y=1,Z='iframe',$='javascript:""',_='position:absolute; width:0; height:0; border:none; left: -1000px;',ab=' top: -1000px;',bb='CSS1Compat',cb='<!doctype html>',db='',eb='<html><head><\/head><body><\/body><\/html>',fb='undefined',gb='DOMContentLoaded',hb=50,ib='Chrome',jb='eval("',kb='");',lb='script',mb='javascript',nb='moduleStartup',ob='moduleRequested',pb='Failed to load ',qb='head',rb='meta',sb='name',tb='mobile::',ub='::',vb='gwt:property',wb='content',xb='=',yb='gwt:onPropertyErrorFn',zb='Bad handler "',Ab='" for "gwt:onPropertyErrorFn"',Bb='gwt:onLoadErrorFn',Cb='" for "gwt:onLoadErrorFn"',Db='#',Eb='?',Fb='/',Gb='img',Hb='clear.cache.gif',Ib='baseUrl',Jb='mobile.nocache.js',Kb='base',Lb='//',Mb='locale',Nb='ru',Ob='locale=',Pb=7,Qb='&',Rb='__gwt_Locale',Sb='_',Tb='Unexpected exception in locale detection, using default: ',Ub=2,Vb='user.agent',Wb='webkit',Xb='safari',Yb='msie',Zb=10,$b=11,_b='ie10',ac=9,bc='ie9',cc=8,dc='ie8',ec='gecko',fc='gecko1_8',gc=3,hc=4,ic='selectingPermutation',jc='mobile.devmode.js',kc='1D04F9A0A30F1FFE10459E25E891FE16',lc='285A2E1CE40444CD7D45C97A3D13548D',mc='4E079C0638DE5067A46965478894887C',nc='en',oc='7733DFF13A81573CB23EA0052B769B59',pc='8A26AEE4D258E500F9C4E60E922B1A7D',qc='A1430B469A000C0F17F24A68EEC6E4C3',rc='B4F55AFE19A75F2318AC15F50507EAE1',sc='D7E7AE8C53F1AB73B6009A3F526315C1',tc='E6BE4441A95AD68984A557D8240C825A',uc='F7B0067B23C99F97B9588113C9F25D35',vc=':',wc='.cache.js',xc='link',yc='rel',zc='stylesheet',Ac='href',Bc='loadExternalRefs',Cc='css/table-widget.css',Dc='css/pager.css',Ec='css/datetimepicker.css',Fc='css/bootstrap.min.css',Gc='css/fonts.css',Hc='css/ionicons.min.css',Ic='css/switcher.css',Jc='css/animate.css',Kc='css/animation.css',Lc='css/font-awesome.css',Mc='css/tree.css',Nc='css/sorm_classic.css',Oc='end',Pc='http:',Qc='file:',Rc='_gwt_dummy_',Sc='__gwtDevModeHook:mobile',Tc='Ignoring non-whitelisted Dev Mode URL: ',Uc=':moduleBase';var q=window;var r=document;t(Q,R);function s(){var a=q.location.search;return a.indexOf(S)!=-1||a.indexOf(T)!=-1}
function t(a,b){if(q.__gwtStatsEvent){q.__gwtStatsEvent({moduleName:U,sessionId:q.__gwtStatsSessionId,subSystem:V,evtGroup:a,millis:(new Date).getTime(),type:b})}}
mobile.__sendStats=t;mobile.__moduleName=U;mobile.__errFn=null;mobile.__moduleBase=W;mobile.__softPermutationId=X;mobile.__computePropValue=null;mobile.__getPropMap=null;mobile.__installRunAsyncCode=function(){};mobile.__gwtStartLoadingFragment=function(){return null};mobile.__gwt_isKnownPropertyValue=function(){return false};mobile.__gwt_getMetaProperty=function(){return null};var u=null;var v=q.__gwt_activeModules=q.__gwt_activeModules||{};v[U]={moduleName:U};mobile.__moduleStartupDone=function(e){var f=v[U].bindings;v[U].bindings=function(){var a=f?f():{};var b=e[mobile.__softPermutationId];for(var c=X;c<b.length;c++){var d=b[c];a[d[X]]=d[Y]}return a}};var w;function A(){B();return w}
function B(){if(w){return}var a=r.createElement(Z);a.src=$;a.id=U;a.style.cssText=_+ab;a.tabIndex=-1;r.body.appendChild(a);w=a.contentDocument;if(!w){w=a.contentWindow.document}w.open();var b=document.compatMode==bb?cb:db;w.write(b+eb);w.close()}
function C(k){function l(a){function b(){if(typeof r.readyState==fb){return typeof r.body!=fb&&r.body!=null}return /loaded|complete/.test(r.readyState)}
var c=b();if(c){a();return}function d(){if(!c){c=true;a();if(r.removeEventListener){r.removeEventListener(gb,d,false)}if(e){clearInterval(e)}}}
if(r.addEventListener){r.addEventListener(gb,d,false)}var e=setInterval(function(){if(b()){d()}},hb)}
function m(c){function d(a,b){a.removeChild(b)}
var e=A();var f=e.body;var g;if(navigator.userAgent.indexOf(ib)>-1&&window.JSON){var h=e.createDocumentFragment();h.appendChild(e.createTextNode(jb));for(var i=X;i<c.length;i++){var j=window.JSON.stringify(c[i]);h.appendChild(e.createTextNode(j.substring(Y,j.length-Y)))}h.appendChild(e.createTextNode(kb));g=e.createElement(lb);g.language=mb;g.appendChild(h);f.appendChild(g);d(f,g)}else{for(var i=X;i<c.length;i++){g=e.createElement(lb);g.language=mb;g.text=c[i];f.appendChild(g);d(f,g)}}}
mobile.onScriptDownloaded=function(a){l(function(){m(a)})};t(nb,ob);var n=r.createElement(lb);n.src=k;if(mobile.__errFn){n.onerror=function(){mobile.__errFn(U,new Error(pb+code))}}r.getElementsByTagName(qb)[X].appendChild(n)}
mobile.__startLoadingFragment=function(a){return G(a)};mobile.__installRunAsyncCode=function(a){var b=A();var c=b.body;var d=b.createElement(lb);d.language=mb;d.text=a;c.appendChild(d);c.removeChild(d)};function D(){var c={};var d;var e;var f=r.getElementsByTagName(rb);for(var g=X,h=f.length;g<h;++g){var i=f[g],j=i.getAttribute(sb),k;if(j){j=j.replace(tb,db);if(j.indexOf(ub)>=X){continue}if(j==vb){k=i.getAttribute(wb);if(k){var l,m=k.indexOf(xb);if(m>=X){j=k.substring(X,m);l=k.substring(m+Y)}else{j=k;l=db}c[j]=l}}else if(j==yb){k=i.getAttribute(wb);if(k){try{d=eval(k)}catch(a){alert(zb+k+Ab)}}}else if(j==Bb){k=i.getAttribute(wb);if(k){try{e=eval(k)}catch(a){alert(zb+k+Cb)}}}}}__gwt_getMetaProperty=function(a){var b=c[a];return b==null?null:b};u=d;mobile.__errFn=e}
function F(){function e(a){var b=a.lastIndexOf(Db);if(b==-1){b=a.length}var c=a.indexOf(Eb);if(c==-1){c=a.length}var d=a.lastIndexOf(Fb,Math.min(c,b));return d>=X?a.substring(X,d+Y):db}
function f(a){if(a.match(/^\w+:\/\//)){}else{var b=r.createElement(Gb);b.src=a+Hb;a=e(b.src)}return a}
function g(){var a=__gwt_getMetaProperty(Ib);if(a!=null){return a}return db}
function h(){var a=r.getElementsByTagName(lb);for(var b=X;b<a.length;++b){if(a[b].src.indexOf(Jb)!=-1){return e(a[b].src)}}return db}
function i(){var a=r.getElementsByTagName(Kb);if(a.length>X){return a[a.length-Y].href}return db}
function j(){var a=r.location;return a.href==a.protocol+Lb+a.host+a.pathname+a.search+a.hash}
var k=g();if(k==db){k=h()}if(k==db){k=i()}if(k==db&&j()){k=e(r.location.href)}k=f(k);return k}
function G(a){if(a.match(/^\//)){return a}if(a.match(/^[a-zA-Z]+:\/\//)){return a}return mobile.__moduleBase+a}
function H(){var i=[];var j=X;function k(a,b){var c=i;for(var d=X,e=a.length-Y;d<e;++d){c=c[a[d]]||(c[a[d]]=[])}c[a[e]]=b}
var l=[];var m=[];function n(a){var b=m[a](),c=l[a];if(b in c){return b}var d=[];for(var e in c){d[c[e]]=e}if(u){u(a,d,b)}throw null}
m[Mb]=function(){var b=null;var c=Nb;try{if(!b){var d=location.search;var e=d.indexOf(Ob);if(e>=X){var f=d.substring(e+Pb);var g=d.indexOf(Qb,e);if(g<X){g=d.length}b=d.substring(e+Pb,g)}}if(!b){b=__gwt_getMetaProperty(Mb)}if(!b){b=q[Rb]}if(b){c=b}while(b&&!__gwt_isKnownPropertyValue(Mb,b)){var h=b.lastIndexOf(Sb);if(h<X){b=null;break}b=b.substring(X,h)}}catch(a){alert(Tb+a)}q[Rb]=c;return b||Nb};l[Mb]={'default':X,'en':Y,'ru':Ub};m[Vb]=function(){var a=navigator.userAgent.toLowerCase();var b=r.documentMode;if(function(){return a.indexOf(Wb)!=-1}())return Xb;if(function(){return a.indexOf(Yb)!=-1&&(b>=Zb&&b<$b)}())return _b;if(function(){return a.indexOf(Yb)!=-1&&(b>=ac&&b<$b)}())return bc;if(function(){return a.indexOf(Yb)!=-1&&(b>=cc&&b<$b)}())return dc;if(function(){return a.indexOf(ec)!=-1||b>=$b}())return fc;return db};l[Vb]={'gecko1_8':X,'ie10':Y,'ie8':Ub,'ie9':gc,'safari':hc};__gwt_isKnownPropertyValue=function(a,b){return b in l[a]};mobile.__getPropMap=function(){var a={};for(var b in l){if(l.hasOwnProperty(b)){a[b]=n(b)}}return a};mobile.__computePropValue=n;q.__gwt_activeModules[U].bindings=mobile.__getPropMap;t(Q,ic);if(s()){return G(jc)}var o;try{k([Nb,Xb],kc);k([Nb,_b],lc);k([Nb,bc],mc);k([nc,_b],oc);k([nc,dc],pc);k([Nb,fc],qc);k([nc,Xb],rc);k([nc,bc],sc);k([Nb,dc],tc);k([nc,fc],uc);o=i[n(Mb)][n(Vb)];var p=o.indexOf(vc);if(p!=-1){j=parseInt(o.substring(p+Y),Zb);o=o.substring(X,p)}}catch(a){}mobile.__softPermutationId=j;return G(o+wc)}
function I(){if(!q.__gwt_stylesLoaded){q.__gwt_stylesLoaded={}}function c(a){if(!__gwt_stylesLoaded[a]){var b=r.createElement(xc);b.setAttribute(yc,zc);b.setAttribute(Ac,G(a));r.getElementsByTagName(qb)[X].appendChild(b);__gwt_stylesLoaded[a]=true}}
t(Bc,R);c(Cc);c(Dc);c(Ec);c(Fc);c(Gc);c(Hc);c(Ic);c(Jc);c(Kc);c(Lc);c(Mc);c(Nc);t(Bc,Oc)}
D();mobile.__moduleBase=F();v[U].moduleBase=mobile.__moduleBase;var J=H();if(q){var K=!!(q.location.protocol==Pc||q.location.protocol==Qc);q.__gwt_activeModules[U].canRedirect=K;function L(){var b=Rc;try{q.sessionStorage.setItem(b,b);q.sessionStorage.removeItem(b);return true}catch(a){return false}}
if(K&&L()){var M=Sc;var N=q.sessionStorage[M];if(!/^http:\/\/(localhost|127\.0\.0\.1)(:\d+)?\/.*$/.test(N)){if(N&&(window.console&&console.log)){console.log(Tc+N)}N=db}if(N&&!q[M]){q[M]=true;q[M+Uc]=F();var O=r.createElement(lb);O.src=N;var P=r.getElementsByTagName(qb)[X];P.insertBefore(O,P.firstElementChild||P.children[X]);return false}}}I();t(Q,Oc);C(J);return true}
mobile.succeeded=mobile();